version: '3.8'

services:
  target-replica-1:
    build: .
    environment:
      - PORT=8001
    ports:
      - "127.0.0.1:8001:8000"

  target-replica-2:
    build: .
    environment:
      - PORT=8002
    ports:
      - "127.0.0.1:8002:8000"

  target-replica-3:
    build: .
    environment:
      - PORT=8003
    ports:
      - "127.0.0.1:8003:8000"
